#!/usr/bin/env bash
set -e
cd isabelle
./bin/isabelle components -I
./bin/isabelle components -a
grep -F 'classpath "$JEDIT_HOME/jars/Console.jar"' contrib/jedit-20211103/etc/settings || patch contrib/jedit-20211103/etc/settings < ../jedit_classpath.patch
./bin/isabelle ghc_setup
./bin/isabelle build -b UTP2

