name: Build
on: [push]
jobs:
  check_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Run build
        run: ./build

